services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mariadb
        networks:
            - laravel_network
        environment:
            - APP_ENV=local
            - APP_DEBUG=true

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    mariadb:
        image: mariadb:latest
        container_name: laravel_mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: onfly
            MYSQL_USER: onfly
            MYSQL_PASSWORD: onfly
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - laravel_network

volumes:
    mariadb_data:
        driver: local

networks:
    laravel_network:
        driver: bridge
