version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        ports:
            - "8000:8000"
        command: php artisan serve --host=0.0.0.0 --port=8000

    db:
        image: mariadb:10.6
        container_name: mariadb_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db_data:
